backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
local_backend:
  url: http://localhost:8081/api/v1

media_folder: static/img
public_folder: /img

search: false;

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Page Title', name: 'page_title', widget: 'string' }
      - {
          label: 'Page Description',
          name: 'page_description',
          widget: 'string',
        }
      - { label: 'Page Route', name: 'page_route', widget: 'string' }
      - { label: 'Page Header', name: 'page_header', widget: 'string' }
      - {
          label: 'Main Page',
          name: 'main_page',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Navigation Order',
          name: 'navigation_order',
          widget: 'number',
          value_type: 'int',
          min: 1,
        }
      - {
          label: 'Page Color',
          name: 'page_color',
          widget: 'color',
          enableAlpha: true,
          default: '#FFF',
        }
      - {
          label: 'Text color',
          name: 'text_color',
          widget: 'color',
          default: '#000',
        }
      - {
          label: 'Section type',
          name: 'section_type',
          widget: 'select',
          options:
            [
              { label: 'Grid', value: 'grid' },
              { label: 'Carousel', value: 'carousel' },
            ],
          default: 'grid',
        }
      - {
          label: 'Images',
          name: 'images',
          widget: 'list',
          min: 1,
          fields:
            [
              { label: 'Image', name: 'image_src', widget: 'image' },
              {
                label: 'Alternative Text',
                name: 'image_alt',
                widget: 'text',
                required: true,
              },
            ],
        }
      - { label: 'Footer Text', name: 'footer_text', widget: 'string' }
