backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "About"
    folder: "src/sections/about/index.md"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "About Me Text", name: "text", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
  
  - name: "section"
    label: "Social Media Section"
    folder: "src/sections/social-media"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "section"}
      - {label: "Section Title", name: "title", widget: "string"}
      - {label: "Section type", name: "type", widget: "select", options: [{label: "Grid", value: "grid"}, {label: "Carousel", value: "carousel"}], default: "grid"}
      - {label: "Order", name: "order", widget: "number", value_type: "int", min: 1}
      - {label: "Images", name: "images", widget: "list", fields: [{label: Image, name: image, widget: image}]}